import { useEffect } from 'react';

/**
 * Sets the tab title and description while a page is mounted, and puts back
 * whatever was there when it unmounts.
 *
 * Most pages use this for navigation inside the app. Blog pages use
 * useBlogMeta instead, which also updates canonical URLs and structured data
 * to match the HTML generated by lib/blog/prerender.ts.
 */
export function useDocumentMeta(title: string, description?: string) {
  useEffect(() => {
    const previousTitle = document.title;
    const tag = document.querySelector<HTMLMetaElement>('meta[name="description"]');
    const previousDescription = tag?.content;

    document.title = title;
    if (tag && description) tag.content = description;

    return () => {
      document.title = previousTitle;
      if (tag && previousDescription !== undefined) tag.content = previousDescription;
    };
  }, [title, description]);
}
